name: Deployment

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Clean Install (npm ci)
        run: npm ci
      - name: Build (npm run build)
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          name: links
          path: ./build
          retention-days: 1
      - name: Deploy Artifact
        uses: actions/deploy-pages@v2.0.4
        with:
          artifact_name: links
          timeout: 180000
      